name: scheduled

on:
  schedule:
    - cron: "00 02 * * 0"

  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      # Create pyhc conda environment
      - name: Provision conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyhc
          environment-file: environment.yml
      - name: conda list
        run: |
          conda list
      # Build Jupyter Book site
      - name: Run jupyter-book build
        run: |
          jupyter-book build .
      # Deploy online preview
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './_build/html'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - scheduled"
          github-deployment-environment: scheduled
          github-deployment-description: "jbook built from environment.yml (scheduled)"
          alias: scheduled
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  build-book-latest-versions:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -l {0}
      steps:
        - uses: actions/checkout@v2
        # Create pyhc conda environment
        - name: Provision conda env
          uses: conda-incubator/setup-miniconda@v2
          with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
            activate-environment: pyhc
            environment-file: environment-latest.yml
        - name: conda list
          run: |
            conda list
        # Build Jupyter Book site
        - name: Run jupyter-book build
          run: |
            jupyter-book build .
        # Deploy online preview
        - name: Deploy to Netlify
          uses: nwtgck/actions-netlify@v1.2
          with:
            publish-dir: './_build/html'
            production-deploy: false
            github-token: ${{ secrets.GITHUB_TOKEN }}
            deploy-message: "Deploy from GitHub Actions - scheduled - latest package versions"
            github-deployment-environment: scheduled-latest-versions
            github-deployment-description: "jbook built from environment-latest.yml (scheduled)"
            alias: scheduled-latest-versions
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          timeout-minutes: 1

